<?php

namespace zegilooo\candidatsFCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * actionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends EntityRepository
{
}
