<?php

namespace zegilooo\candidatsFCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnelRepository extends EntityRepository
{
}
